# DATA_MODEL_SOLVER CONFIGS:
# Ours-SFI
DATA_INFO:
  dataset_name: 'sth_else'
  num_classes: 174
  json_data_train: 'dataset_splits/sth_else/compositional/train.json'
  json_data_val: 'dataset_splits/sth_else/compositional/validation.json'
  json_file_labels: 'dataset_splits/sth_else/compositional/labels.json'
  tracked_boxes: 'dataset/sth_else/BBOX/DET/COM/anno.pkl'
  vis_info: True
  coord_info: True
  category_info: True
  num_frames: 16
  if_augment: True
MODEL_INFO:
  model: 'region'
  global_mode: default
  joint: T
  reasoning_module: 'STRG' # Spatio-Temporal Compositional Reasoning
  reasoning_mode: 'ST' # S, T, ST
  LSTM_flow: default
  multiple_interaction: default
  pred: default
  pred_w: default
SOLVER_INFO:
  lr: default
  lr_steps: 5 10 15 # 24 35 45
  epochs: 20 # 50
  batch_size: 72
  workers: 16
  ckpt: default
                
