# DATA_MODEL_SOLVER CONFIGS:
DATA_INFO:
  dataset_name: 'sth_else'
  num_classes: 86
  json_data_train: 'dataset_splits/sth_else/fewshot/finetune_5shot_train.json'
  json_data_val: 'dataset_splits/sth_else/fewshot/finetune_5shot_validation.json'
  json_file_labels: 'dataset_splits/sth_else/fewshot/finetune_labels.json'
  tracked_boxes: 'dataset/sth_else/BBOX/DET/FEWSHOT/anno.pkl'
  vis_info: default
  coord_info: default
  category_info: default
  num_frames: 8
  if_augment: False
MODEL_INFO:
  model: 'global_coord_latent_nl'
  global_mode: default
  joint: default
  reasoning_module: default
  reasoning_mode: default
  LSTM_flow: default
  multiple_interaction: default
  pred: default
  pred_w: default
SOLVER_INFO:
  lr: default
  # lr_steps: 5 10 15 # 24 35 45
  # epochs: 20 # 50
  lr_steps: default
  epochs: default
  batch_size: 72
  workers: default
  ckpt: default
  fine_tune: 'ckpt/STHELSE/FEWSHOT/DET/STIN/base/exp_best.pth.tar'

                
