# DATA_MODEL_SOLVER CONFIGS:
# Ours-base with appearance features for 10-shot.
DATA_INFO:
  dataset_name: 'sth_else'
  num_classes: 86
  json_data_train: 'dataset_splits/sth_else/fewshot/finetune_10shot_train.json'
  json_data_val: 'dataset_splits/sth_else/fewshot/finetune_10shot_validation.json'
  json_file_labels: 'dataset_splits/sth_else/fewshot/finetune_labels.json'
  tracked_boxes: 'dataset/sth_else/BBOX/DET/FEWSHOT/anno.pkl'
  vis_info: True
  coord_info: True
  category_info: True
  num_frames: 16
  if_augment: False
MODEL_INFO:
  model: 'region'
  global_mode: default
  joint: T
  reasoning_module: 'pool_T' # Spatio-Temporal Compositional Reasoning
  reasoning_mode: default # S, T, ST
  LSTM_flow: default
  multiple_interaction: default
  pred: default
  pred_w: default
SOLVER_INFO:
  lr: default
  # lr_steps: 5 10 15 # 24 35 45
  # epochs: 20 # 50
  lr_steps: 24 35 45
  epochs: 50
  batch_size: 72
  workers: 16
  ckpt: default
  fine_tune: 'ckpt/STHELSE/FEWSHOT/DET/OURS_BASE/base/exp_best.pth.tar'
                
