# DATA_MODEL_SOLVER CONFIGS:
DATA_INFO:
  dataset_name: 'sth_else'
  num_classes: 174
  json_data_train: default
  json_data_val: default
  json_file_labels: default
  vis_info: T
  coord_info: T
  category_info: T
  num_frames: 16
  if_augment: T
MODEL_INFO:
  model: 'REGION'
  global_mode: default
  joint: default
  reasoning_module: 'compositional'
  reasoning_mode: 'ST' # S, T, ST
  LSTM_flow: T
  multiple_interaction: T
  pred: T
  pred_w: 5
SOLVER_INFO:
  lr: default
  lr_steps: [24, 35, 45]
  epochs: 50
  batch_size: 72
  workers: 16
  ckpt: default
                
